---

- name: Combine debconf settings
  set_fact:
    packages__debconf_settings_combined: |
      {{
        (packages__debconf_settings       | d([]) | list) +
        (packages__debconf_group_settings | d([]) | list) +
        (packages__debconf_host_settings  | d([]) | list)
      }}

- name: Apply debconf settings
  debconf:
    name: '{{ item.name }}'
    question: '{{ item.question|d(omit) }}'
    value: '{{ item.value|d() }}'
    vtype: '{{ item.vtype|d() }}'
  when: (item.name in packages__class_install or (item.when_package|d() and item.when_package in packages__class_install))
  with_items: '{{ packages__debconf_settings_combined }}'
