---

- name: Install packages via APT
  apt:
    name: '{{ q("flattened", packages__class_install|d([])) }}'
    state: '{{ packages__deploy_state }}'
    install_recommends: '{{ packages__deploy_install_recommends|bool }}'
    force: '{{ packages__deploy_force|bool }}'
    update_cache: '{{ packages__deploy_update_cache|bool }}'
    cache_valid_time: '{{ packages__deploy_cache_valid_time|d(omit) }}'
    default_release: '{{ packages__deploy_default_release|d(omit) }}'
    dpkg_options: '{{ packages__deploy_dpkg_options|d(omit) }}'
  when: (ansible_pkg_mgr == 'apt')

- name: Remove packages via APT
  apt:
    name: '{{ q("flattened", packages__class_absent|d([])) }}'
    state: 'absent'
    install_recommends: '{{ packages__deploy_install_recommends|bool }}'
    purge: '{{ packages__deploy_purge|bool }}'
    force: '{{ packages__deploy_force|bool }}'
    update_cache: '{{ packages__deploy_update_cache|bool }}'
    cache_valid_time: '{{ packages__deploy_cache_valid_time|d(omit) }}'
    default_release: '{{ packages__deploy_default_release|d(omit) }}'
    dpkg_options: '{{ packages__deploy_dpkg_options|d(omit) }}'
  when: (ansible_pkg_mgr == 'apt')
