---

- name: Include item variable
  include_vars: '{{ item }}'

- name: Combine variables
  set_fact:
    packages__blacklist_by_role_combined: '{{
      ((packages__blacklist_by_role_combined | d([]) | list) +
      (packages__blacklist_by_role | d([]) | list)) | unique }}'
    packages__whitelist_by_role_combined: '{{
      ((packages__whitelist_by_role_combined | d([]) | list) +
      (packages__whitelist_by_role | d([]) | list)) | unique }}'
