---

- name: Include distribution specific variables
  include: include_item_vars.yml
  when: (item|d() and packages__load_distribution_vars)
  with_first_found:
    - skip: True
      files:
        - '{{ (ansible_distribution + ".yml") | replace(" ", "_") }}'
      paths: 'vars'

- name: Include distribution release specific variables
  include: include_item_vars.yml
  with_first_found:
    - skip: True
      files:
        - '{{ (ansible_distribution + "_" + ansible_distribution_release + ".yml") | replace(" ", "_") }}'
      paths: 'vars'

- name: Include distribution release backports specific variables
  include: include_item_vars.yml
  when: (item|d() and packages__load_distribution_backports_vars)
  with_first_found:
    - skip: True
      files:
        - '{{ (ansible_distribution + "_" + ansible_distribution_release + "_backports.yml") | replace(" ", "_") }}'
      paths: 'vars'

- name: Preserve current packages__targets for later use
  set_fact:
    packages__targets_real: '{{ packages__targets }}'
  when: (packages__load_distribution_additional_releases or packages__load_distribution_additional)

- name: Run include additional vars tasks
  include: include_item_vars.yml
  when: (item|d())
  with_items: '{{
    ((packages__load_distribution_additional_releases | list)
      | map("regex_replace", "^", ((ansible_distribution|d("")|replace(" ", "_")) + "_"))
      | map("regex_replace", "$", ".yml") | list) +
    ((packages__load_distribution_additional | list)
      | map("regex_replace", "$", ".yml") | list) }}'

- name: Restore packages__targets_real to packages__targets
  set_fact:
    packages__targets: '{{ packages__targets_real | d(packages__targets) }}'
    packages__blacklist_by_vars: '{{
      ((packages__blacklist_by_vars_combined | d([]) | list) +
      (packages__blacklist_by_vars | d([]) | list)) | unique }}'
    packages__blacklist_revoke_by_vars: '{{
      ((packages__blacklist_revoke_by_vars_combined | d([]) | list) +
      (packages__blacklist_revoke_by_vars | d([]) | list)) | unique }}'
    packages__whitelist_by_vars: '{{
      ((packages__whitelist_by_vars_combined | d([]) | list) +
      (packages__whitelist_by_vars | d([]) | list)) | unique }}'

- name: Combine variables
  set_fact:
    packages__classes_combined: |
      {{ packages__classes|d({}) | combine(packages__classes_additional|d({})) }}
