---

- name: Include item variable
  include_vars: '{{ item }}'

- name: Combine variables
  set_fact:
    packages__blacklist_by_vars_combined: '{{
      ((packages__blacklist_by_vars_combined | d([]) | list) +
      (packages__blacklist_by_vars | d([]) | list)) | unique }}'
    packages__blacklist_revoke_by_vars_combined: '{{
      ((packages__blacklist_revoke_by_vars_combined | d([]) | list) +
      (packages__blacklist_revoke_by_vars | d([]) | list)) | unique }}'
    packages__whitelist_by_vars_combined: '{{
      ((packages__whitelist_by_vars_combined | d([]) | list) +
      (packages__whitelist_by_vars | d([]) | list)) | unique }}'
    packages__name_remapping_by_vars_combined: '{{
      (packages__name_remapping_by_vars_combined | d({}))
      | combine(packages__name_remapping_by_vars | d({})) }}'
