---

- name: Test for supported package managers
  assert:
    that: ansible_pkg_mgr in [
            'apt',
          ]
  when: (packages__mode == 'deploy')
  tags:
    - 'role::packages:debconf'

- name: Combine variables
  set_fact:
    packages__debconf_settings_combined: |
      {{
        (packages__debconf_settings       | d([]) | list) +
        (packages__debconf_group_settings | d([]) | list) +
        (packages__debconf_host_settings  | d([]) | list)
      }}
  tags:
    - 'role::packages:debconf'

- name: Run prepare deploy tasks
  include: prepare_deploy.yml
  when: (packages__mode == 'deploy')
  tags:
    - 'role::packages:debconf'

- name: Run deploy tasks
  include: deploy.yml
  when: (packages__mode == 'deploy')

- name: Run export tasks
  include: export.yml
  when: (packages__mode == 'export')
  with_items: '{{ packages__export_distributions }}'
