---

- name: Run prepare deploy tasks
  include: prepare_deploy.yml
  when: (packages__mode == 'deploy')
  tags: [ 'role::packages:debconf' ]

- name: Run deploy tasks
  include: deploy.yml
  when: (packages__mode == 'deploy')

- name: Run export tasks
  include: export.yml
  loop_control:
    loop_var: 'packages__export_distribution_item'
  when: (packages__mode == 'export')
  with_items: '{{ packages__export_distributions }}'
