---

- name: Run include vars tasks
  include: include_vars.yml

- name: Set packages__export_key_name to packages__class_install
  set_fact:
    packages__export_key_name: 'packages__class_install'

- name: Write package list to temporary file
  template:
    src: 'package_yaml.j2'
    dest: '/tmp/ansible-ypid-packages__class_install.yml'
  no_log: True
  changed_when: False
  always_run: True
  delegate_to: 'localhost'
  with_items: '{{ packages__host_class }}'

- name: Set packages__export_key_name to packages__class_absent
  set_fact:
    packages__export_key_name: 'packages__class_absent'

- name: Write absent package list to temporary file
  template:
    src: 'package_yaml_absent.j2'
    dest: '/tmp/ansible-ypid-packages__class_absent.yml'
  no_log: True
  changed_when: False
  always_run: True
  delegate_to: 'localhost'
  with_items: '{{ packages__host_class }}'

- name: Include templated package lists
  include_vars: '/tmp/ansible-ypid-{{ item }}.yml'
  with_items:
    - 'packages__class_install'
    - 'packages__class_absent'

- name: Ensure temporary package list files are absent
  file:
    path: '/tmp/ansible-ypid-{{ item }}.yml'
    state: 'absent'
  always_run: True
  delegate_to: 'localhost'
  changed_when: False
  with_items:
    - 'packages__class_install'
    - 'packages__class_absent'

- name: Fail when a package has a conflicting state
  fail:
    msg: 'The following packages are required to be installed and at the same time to should be absent: {{ packages__class_install | intersect(packages__absent_for_class[packages__host_class]|d([])) }}'
  when: (packages__class_install | intersect(packages__absent_for_class[packages__host_class]|d([])))

- name: Apply debconf settings
  debconf:
    name: '{{ item.name }}'
    question: '{{ item.question|d(omit) }}'
    value: '{{ item.value|d() }}'
    vtype: '{{ item.vtype|d() }}'
  when: (packages__mode == 'deploy' and packages__debconf_enabled and ansible_os_family == 'Debian' and
         (item.name in packages__class_install or (item.when_package|d() and item.when_package in packages__class_install)))
  with_items: '{{ packages__debconf_settings_combined }}'
