---

## FIXME: Support absent with different YAML key name.
## FIXME: Ensure absent
- name: Export Linuxmuster.net package lists
  hosts: localhost
  gather_facts: False
  vars:
    ansible_pkg_mgr: 'apt'
    ansible_virtualization_role: 'host'
    packages__mode: 'export'
    packages__export_format: 'yaml'
    packages__export_key_name: 'linuxmuster_net_client__packages_preset_ypid'
    packages__export_key_absent_name: 'linuxmuster_net_client__packages_preset_ypid_absent'
    packages__export_directory: '{{ inventory_dir | realpath }}/../../apt_package_lists'
    packages__contrib_enabled: True
    packages__non_free_enabled: True
    packages__export_classes:
      - 'client_school_linuxmuster'
    packages__export_distributions:

      - ansible_distribution: 'Ubuntu'
        ansible_distribution_release: 'trusty'

  roles:
    - role: ypid.packages
